on: [push, pull_request]
name: rector
jobs:
  rector-ci:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      -   run: composer install --no-progress --ansi
      -   run: vendor/bin/rector process --ansi
